# This file contains confinguration options for the MPF itself, including
# default settings for your pinball machines.

# You should create specific subfolders for each game you want to make and put
# config files there to override these defaults.


# Configuration for the MPF framework itself

MPF:
    system_modules:  # order is important here
        timing.Timing
        events.EventManager
        switch_controller.SwitchController
        ball_controller.BallController
        language.Language
        modes.ModeController
        display.DisplayController
        show_controller.ShowController

    device_modules:
        driver.Driver
        switch.Switch
        matrix_light.MatrixLight
        led.LED
        gi.GI
        autofire.AutofireCoil
        ball_device.BallDevice
        drop_target.DropTarget
        drop_target.DropTargetBank
        target.Target
        target.TargetGroup
        rollover.Rollover
        rollover.RolloverGroup
        flipper.Flipper
        diverter.Diverter
        score_reel.ScoreReel
        score_reel.ScoreReelGroup
        flasher.Flasher

    display_modules:
        elements:
            - text
            - virtualdmd
            - image
            - animation
            - shape
            - movie
        modules:
            dmd.DMD
        transitions:
            move_out: move_out.MoveOut
            move_in: move_in.MoveIn
        decorators:
            blink: blink.Blink
    paths:
        scriptlets: scriptlets
        plugins: plugins
        shows: shows
        audits: audits/audits.yaml
        sounds: sounds
        machine_files: machine_files
        config: config
        fonts: fonts
        images: images
        animations: animations
        movies: movies
        modes: modes
    auto_load_shows: True
    default_pulse_ms: 10
    default_debounce_ms: 0  # fast only

# Default settings for machines. All can be overridden

Machine:
    HZ: 30
    Balls Installed: 1
    Min Balls: 1
    Max Balls: 10

Hardware:
    Platform: virtual

P_ROC:
    lamp_matrix_strobe_time: 100
    watchdog_time: 1000
    use_watchdog: True

LEDSettings:
    brightness_compensation: 1.0
    default_led_fade_ms: 100

Game:
    Balls per game: 3
    Max players per game: 4

MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

OSC:
    machine_ip: auto
    machine_port: 8000
    approved_client_ips: any
    client_port: 9000
    debug_messages: false
    client_updates:
        switches
        lights
        data

Auditor:
    save_events:
        game_started
        ball_ended
        game_ended
    num_player_top_records: 10
    audit:
        shots
        switches
        events
        player
    events:
        ball_search_begin_phase1
        game_started
        game_ended
    player:
        score

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    If ball search fails: Keep Looking

LogicBlocks:

    Counters:

        tilt:
            count_events: sw_tilt
            event_when_hit: tilt_hit
            count_complete_value: 3
            events_when_complete: tilt
            multiple_hit_window: 500ms
            reset_each_ball: yes

        slam_tilt:
            count_events: sw_slamTilt
            count_complete_value: 1
            events_when_complete: slam_tilt

DisplayDefaults:
    Text:
        font: default
        size: 10
        opaque: false
        v_pos: center
        h_pos: center
        x: 0
        y: 0
        time: 0s
        text_color: ffffff
        background_color: 000000
        text_shade: 15
        background_shade: 0
        antialias: False

Fonts:
    default:
        file: Quadrit.ttf
        size: 10
        crop_top: 2
        crop_bottom: 3
    space title huge:
        file: DEADJIM.TTF
        size: 29
        antialias: yes
        crop_top: 3
        crop_bottom: 3
    space title:
        file: DEADJIM.TTF
        size: 21
        antialias: yes
        crop_top: 2
        crop_bottom: 3
    medium:
        file: pixelmix.ttf
        size: 8
        crop_top: 1
        crop_bottom: 1
    small:
        file: smallest_pixel-7.ttf
        size: 9
        crop_top: 2
        crop_bottom: 3
    tall title:
       file: big_noodle_titling.ttf
       size: 20

TextStrings:
    volume_zero: OFF
    volume_max: MAX

AssetDefaults:
    Images:
        default:
            load: preload
        screen:
            target: screen
        dmd:
            target: dmd
    Animations:
        default:
            load: preload
            target: dmd
        screen:
            load: preload
            target: screen
    Sounds:
        default:
            track: sfx
            load: preload
        voice:
            track: voice
            load: preload
        sfx:
            track: sfx
            load: preload
        music:
            track: music
            load: preload
    Shows:
        default:
            load: preload
    Movies:
        default:
            load: preload
