Mode:
    start_events: start_mode1_acmag
    end_events: timer_mode_countdown_complete
    priority: 300

Timers:
    mode_countdown:
        start_value: 30
        end_value: 0
        direction: down
        start_running: true

SlidePlayer:
    timer_mode_countdown_tick:
      - type: text
        text: "COUNTDOWN: %ticks"
        font: small
        v_pos: bottom
      - type: text
        text: SHOOT THE LEFT RAMP
        decorators:
            type: blink
            repeats: -1
            on_secs: .3
            off_secs: .3

LightPlayer:
    mode_mode1_acmag_started:
        lights: l_left_ramp_arrow
        script: flash
        tocks_per_sec: 4
        repeat: yes